config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              controllers: {registrations: 'users/registrations',
              :omniauth_callbacks => "users/omniauth_callbacks"}

  authenticated :user do 
    root :to => 'frames#archived', as: :authenticated_root
  end
  root 'pages#landing'
  resources :u, :controller => 'users' do
    get :edit_tag, on: :member
    get :edit_picture, on: :member 
  end
  get 'archived' => 'frames#archived'
  get 'signup' => 'pages#signup'
  get 'career' => 'pages#career'
  get 'team' => 'pages#team'
  get 'about' => 'pages#story'
  get 'search' => 'pages#search'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'landing' => 'pages#landing'
  get 'getting_started' => 'pages#getting_started'
  resources :posts do 
    get :post_content, on: :member
  end
  resources :frames
  resources :reports

  resources :likes, only: [:create,:destroy]

  get 'users/:user_id', to: 'posts#index', as: :abcd

end

app/views/shim/_header.html.erb
<!--<style>
.menu-icon {
    width: 35px;
    height: 2px;
    background-color: black;
    margin: 6px 0;
    background-color: #fff;
    transition: 0.4s;
}

.menu-icon-container {
    margin-top: 10px;
    float: left;
    margin-right: 15px;
    cursor: pointer;
}
.sidenav {
    height: 100%;
    width: 0;
    position: fixed;
    top: 0;
    left: 0;
    background-color:  #1a1a1a;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 0px;
    z-index: 2000;

}

.sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
    transition: 0.3s
}

.navbar-search {
    margin-top: 10px;

}

.change .bar-1 {
    -webkit-transform: translate(-35px);
    transform: translate(-35px) ;
}


.change .bar-2 {
    -webkit-transform: translate(-35px);
    transform: translate(-35px) ;

}

.change .bar-3 {
    -webkit-transform: translate(-35px);
    transform: translate(-35px) ;

}

.mobile-search-icon {
    float: right;
}

.mobile-search-bar {
    position: fixed;
    z-index: 1;
}



@media screen and (max-width: 1224px) {
    .search-bar {
        display: block;
    }
    .navbar-links {
        display: block;
    }

    .mobile-search-icon {
        display: none;

    }
    .mobile-search-bar {
        display: none;
    }
}

@media screen and (max-width: 763px) {
    .search-bar {
        display: none;
    }
    .navbar-links {
        display: none;
    }
    .mobile-search-icon {
        display: none ;
    }
    .mobile-search-bar {
        display: none;
    }

}

@media screen and (max-width: 480px) {
    .search-bar {
        display: none;
    }
    .navbar-links {
        display: none;
    }
    .mobile-search-icon {
        display: block;
        float: right;
        color: #fff;
        margin-right: 10px;
        padding-top: 16px;
        font-size: 20px;
        cursor: pointer;
    }
    .mobile-search-bar {
        display: block;
         background-color: #1a1a1a;
    }
    .menu-icon-container {
        margin-left: 5px;
    }

}

.navbar-search input[type=text]{
    width: 88%;
    height: 30px;
    border: 2px solid transparent;
    border-radius: 2px;
    border-bottom-left-radius: 0px;
    border-top-left-radius: 0px;
    background-color: grey;
    color: #fff;
    outline: none;
    font-family: 'Assistant', sans-serif;
}

.navbar-search input[type=text]:focus {
    border: 1px solid transparent;
    transition: 0.2s;

}

::-webkit-input-placeholder {
   padding-left: 10px;
}

:-moz-placeholder { /* Firefox 18- */
   padding-left: 10px;
}

::-moz-placeholder {  /* Firefox 19+ */
    padding-left: 10px;
}

:-ms-input-placeholder {  
    padding-left: 10px;
}

input:focus::-webkit-input-placeholder { color:transparent; }

.search-icon-holder {
    background-color: #bababa;
    border: 2px solid transparent;
}

#myBody {
    transition: 0.2s;
}


</style>
 <meta name="viewport" content="width=device-width" />
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container fluid">
    <div class = "menu-icon-container" onclick= "openNav()">
        <div class = "menu-icon bar-1"></div>
        <div class = "menu-icon bar-2"></div>
        <div class = "menu-icon bar-3"></div>
    </div>
        <a class="navbar-brand" href="/">Snapdshort</a>
        
            <div class = "col-sm-5 col-md-5 search-bar">
            <%= form_tag search_path, :method => 'get' , class: "navbar-search" do %>
                <div class="input-group input-group-md">
                <span class="input-group-addon search-icon-holder"><i class="fa fa-search"></i></span>
                    <%= text_field_tag :search, params[:search], placeholder: "Search" %>
                </div>
            <% end %>
            </div>

            <div class = "mobile-search-bar col-xs-6">
            <%= form_tag search_path, :method => 'get' , class: "navbar-search" do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search", class: "search-box" %>
            <% end %>
            </div>
            <span class = "mobile-search-icon"><i class="fa fa-search" aria-hidden="true"></i></span>
        
        <% if user_signed_in? %>
        	<ul class="nav navbar-nav navbar-right navbar-links">
        		<li class= "dropdown">
        			<a href='#' class="dropdown-toggle" data-toggle = "dropdown">
        			 <i class="fa fa-user" aria-hidden="true"></i><b class = "caret"></b>
        			</a>
        			<ul class = "dropdown-menu">
                        <li> <%= link_to u_path(current_user) do %> 
                            <i class = "fa fa-user" aria-hidden="true"></i>
                            My profile
                        <% end %> </li>
        				<li><%= link_to edit_user_registration_path do %>
                            <i class="fa fa-cog" aria-hidden="true"></i>
                            Edit profile
                        <% end %>
                        </li>
        				<li class = "divider"></li>
        				<li><%= link_to destroy_user_session_path, method: :delete do %>
                            <i class="fa fa-sign-out" aria-hidden="true"></i>
                            Sign out
                        <% end %>            
                        </li>
        			</ul>
        		</li>
        	</ul>
        <% else %>
     		<ul class="nav navbar-nav navbar-right navbar-links">
      			<li><%= link_to new_user_session_path, id: "login" do %>
      					<i class="fa fa-sign-in" aria-hidden="true"></i> Login
      				<% end %>
      			</li>
                <li> <%= link_to 'Join' , signup_path %> </li>
    		</ul>
    	<% end %>
    </div>
</header>

<%= render 'shared/rightnav' %>


<script type="text/javascript">
function openNav() {
    var screenWidth = document.documentElement.clientWidth;
    var sidenav = document.getElementById("mySidenav");
    if(screenWidth > 1224) {
        sidenav.style.width = "23%";
    } else if (screenWidth > 765) {
        sidenav.style.width = "40%";
    } else {
        sidenav.style.width = "100%";
    }
    document.getElementsByClassName("menu-icon-container")[0].classList.toggle("change");
    document.getElementsByClassName("close-icon-container")[0].classList.toggle("close-change");
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0%";
    document.getElementsByClassName("menu-icon-container")[0].classList.toggle("change");
    document.getElementsByClassName("close-icon-container")[0].classList.toggle("close-change");
}

function fitMobile() {
    var screenWidth = document.documentElement.clientWidth;

    if(screenWidth > 1224) {
        $('.mobile-search-icon').hide();
        $('.mobile-search-bar').hide();

    } else if (screenWidth > 763) {
        $('.mobile-search-icon').hide();
        $('.mobile-search-bar').hide();

    } else  {
          $('.mobile-search-icon').show();
        $('.mobile-search-bar').hide();

    }
}
$(document).on('turbolinks:load', fitMobile);
$(window).resize(fitMobile);
$('.mobile-search-icon').on('click', function() {
    $('.mobile-search-bar').toggle();
})

$('.fa-cog').on('mouseenter',function() {
    $(this).addClass('fa-spin');
});

$('.fa-cog').on('mouseleave',function() {
    if($(this).hasClass('fa-spin')) {
        $(this).removeClass('fa-spin');
    };
});
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
});

</script> !-->
<style>
    
    #navbarhead {
        list-style: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: white;
        padding-bottom: 10px;
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 5px;
        border-bottom: 1.5px #d3d3d3 solid;
        z-index: 99999999;

    }

    li {
        padding-top: 7.5px;
        float: left;
        font-family: Heebo;
        letter-spacing: 0.5px;
        font-size: 25px;
    }
    li a {
    display: block;
    color: black;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

/*li a:hover:not(.active) {
    background-color: gray;
    transition: 0.3s;
}*/

.active {
    background-color: #4CAF50;
}
#nav-logo {
    width: 170px;
    height: 30px;
    float: right;
    margin-top: 4px;
}
#nav-li-logo {
    margin-top: 10px;
    float: right;
}
#menu-icon {
    margin-top: 8px;
}
.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #f1f1f1}

#menu-icon:hover .dropdown-content {
    display: block;
}
.session-links:hover {
    text-decoration: none;
}

</style>

<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Heebo:100" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
</head>
<body>
    <ul id = "navbarhead">
        <li id = "menu-icon"><i class = "material-icons" style="font-size: 48px">&#xE5D2;</i>
            <div class = "dropdown-content">
                <a href="/">Home</a>
                <%= link_to "Archive", archived_path %>
                <%= link_to "Getting Started" , getting_started_path %>
                <%= link_to "Active", frames_path, method: :get %>
            </div>
        </li>
    <%if !user_signed_in? %>
        <li><%= link_to "Login" , new_user_session_path , class: "session-links"%></li>
        <li><%= link_to "Signup" , signup_path, class: "session-links" %></li>
    <% else %>
        <li><%= link_to "Logout" ,destroy_user_session_path, method: :delete , class: "session-links"%></li>
    <% end %>
        <li id = "nav-li-logo"><img src = "/assets/logo.png" id = "nav-logo"></li>
    </ul>
</body>
</html>