config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              controllers: {registrations: 'users/registrations',
              :omniauth_callbacks => "users/omniauth_callbacks"}

  authenticated :user do 
    root :to => 'frames#archived', as: :authenticated_root
  end
  root 'pages#landing'
  resources :u, :controller => 'users' do
    get :edit_tag, on: :member
    get :edit_picture, on: :member 
  end
  get 'archived' => 'frames#archived'
  get 'signup' => 'pages#signup'
  get 'career' => 'pages#career'
  get 'team' => 'pages#team'
  get 'about' => 'pages#story'
  get 'search' => 'pages#search'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'landing' => 'pages#landing'
  get 'getting_started' => 'pages#getting_started'
  resources :posts do 
    get :post_content, on: :member
  end
  resources :frames
  resources :reports

  resources :likes, only: [:create,:destroy]

  get 'users/:user_id', to: 'posts#index', as: :abcd

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  after_create :skip_conf!
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :frames
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :notifications
  mount_uploader :profile_pic , PictureUploader
  validates :name,	presence:true,
  					length: {maximum: 65}

  def slug
    name.downcase.gsub(" ", "-")
  end

  def to_param
    "#{id}-#{slug}"
  end

  def skip_conf!
  	self.confirm! if Rails.env.development?
    self.confirm! if Rails.env.production?
  end


  def like(post)
    self.likes.create!(post_id: post.id)
    self.notifications.create!(post_id: post.id, liked_user_id: post.user.id)
  end

  def unlike(post)
    like = self.likes.find_by(post_id: post.id)
    notification = self.notifications.find_by(post_id: post.id, liked_user_id: post.user.id)
    like.destroy!
    notification.destroy!
  end

  def liked?(post)
    self.likes.find_by(post_id: post.id)
  end

   def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      end
  end
def new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
     super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up)<< :name
end

def configure_account_update_params
  devise_parameter_sanitizer.for(:account_update)<< :name
end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    @skip_footer = true
  end

  # POST /resource/sign_in
  def create
     super
  end

  # DELETE /resource/sign_out
  def destroy
     super
  end

  protected

  # You can put the params you want to permit in the empty array.
   def configure_sign_in_params
     devise_parameter_sanitizer.for(:sign_in) << :attribute
   end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
	
	def show 
		@user = User.find(params[:id])
	end

	def edit_tag
		@user = User.find(params[:id])
	end

	def edit_picture
		@user = User.find(params[:id])
	end

	def update 
		@user = User.find(params[:id])
		respond_to do |format|
			if @user.update(user_params) 
				format.js
			end
		end
	end

	private 

		def user_params
			params.require(:user).permit(:bio,:profile_pic)
		end
end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    User.new
  end

  def resource_class 
     User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/users/_edit_profilepic.html.erb
<%= form_for u, url: u_path(u),remote: true do |f| %> 
	<%= f.file_field :profile_pic, class: "edit-profile-pic-input" %>

	<div class = "modal-footer">
		<%= f.submit "Save changes" , class: "btn btn-primary edit-save-button btn-sm" %>
		<button type="button" class="btn btn-secondary edit-close-button btn-sm" data-dismiss="modal">Close</button>
	</div>
<% end %>

app/views/users/_edit_tagline.html.erb
<%= form_for u, url: u_path(u),remote: true do |f| %> 
	<%= f.text_area :bio, class: "edit-tagline-input" %>

	<div class = "modal-footer">
		<%= f.submit "Save changes" , class: "btn btn-primary edit-save-button btn-sm" %>
		<button type="button" class="btn btn-secondary edit-close-button btn-sm" data-dismiss="modal">Close</button>
	</div>
<% end %>

app/views/users/edit_picture.js.erb
var tagFormModal = $('#profilePicEditModal').find('.modal-body');
tagFormModal.html('<%= j render partial: "users/edit_profilepic", locals: {u: @user} %> ');

app/views/users/edit_tag.js.erb
var tagFormModal = $('#tagEditModal').find('.modal-body');
tagFormModal.html('<%= j render partial: "users/edit_tagline", locals: {u: @user} %> ');

app/views/users/show.html.erb
<style>
 html { overflow-y: scroll; }

body { font-family: sans-serif; 
  
}


/* ---- grid ---- */

.grid {
  background: transparent;
  margin-top: 270px;
}

/* clear fix */
.grid:after {
  content: '';
  display: block;
  clear: both;
}

/* ---- .grid-item ---- */

.grid-sizer,
.grid-item {
  width: 33.333%;
}
@media screen and (max-width: 2900px) {
  .grid-sizer { width: 33.333%; }
  .grid-item { width: 33.333%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
   .close-display-post {
    color: gray;
  }
} 
@media screen and (max-width: 1224px) {
  .grid-sizer { width: 50%; }
  .grid-item { width: 50%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
   .close-display-post {
    color: gray;
  }
  
}


@media screen and (max-width: 720px) {
  .grid-sizer { width: 50%; }
  .grid-item { width: 50%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
   .close-display-post {
    color: #fff;
  }
  
}

@media screen and (max-width: 480px) {
  .grid-sizer { width: 100%; }
  .grid-item { width: 100%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
   .close-display-post {
    color: #fff;
  }
  
}

.grid-item {
  float: left;
  padding: 3px;
}

.grid-item img {
  display: block;
  max-width: 100%;
  border-top-right-radius: 1%;
  border-top-left-radius: 1%;
}

.grid-item a {
  text-decoration: none;
  color: black;
}

.card {
  border: 1px solid #ececec;
  border-radius: 1%;
  background: #ececec;
}

.card-block {
  background: #ececec;
  padding-bottom: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
.noselect {
  -webkit-touch-callout: none; /* iOS Safari */
  -webkit-user-select: none;   /* Chrome/Safari/Opera */
  -khtml-user-select: none;    /* Konqueror */
  -moz-user-select: none;      /* Firefox */
  -ms-user-select: none;       /* Internet Explorer/Edge */
  user-select: none; 
  user-drag: none; 
user-select: none;
-moz-user-select: none;
-webkit-user-drag: none;
-webkit-user-select: none;
-ms-user-select: none;          /* Non-prefixed version, currently
                                  not supported by any browser */
}
.modal-picture-container img{
  display: block;
  height: auto;
  width:100%;
}  

.about-user-container {
  background-color: transparent;
  font-family: 'Assistant' , sans-serif;
  margin-top: 65px;
}

.about-user-picture-container {
  height: 200px;
  width: 200px;
  <% if @user.profile_pic != nil%>
    background-image: url('<%= @user.profile_pic.url%>');
  <% end %>
  <% if @user.profile_pic == nil %>
    background-image: url(http://1.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=280);
  <% end %>
   background-size: cover;
    background-repeat: no-repeat;
    border-radius: 100%;
}

.text-container {
  margin-left: 65px;
}
.fa-pencil-square-o {
  margin-left: 5px;
}
.fa-pencil-square-o:hover {
  color: gray;
  transition: 0.1s;
}

.after {
  z-index: 1;
  position: absolute;
  top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0);
    display: block;
}
.card-text {
  font-size: 1.2em;
}
.close-display-post {
  position: absolute;
  z-index: 10000;
  left: 95%;
  cursor: pointer;
  font-size: 2em;
}

.btn-share{
  margin: 2px;
  color: #fff;
  font-family: 'Assistant', sans-serif;
  border-radius: 0px;
}
.btn-share:hover {
  color: #fff;
}
.btn-share:focus {
  color: #fff;
  outline: none;
}

.btn-facebook {
  background-color: #3b5998;
}
.btn-twitter {
  background-color: #55acee;
}
.btn-google-plus {
  background-color: #dd4b39;
}
.edit-tagline-input {
  width: 100%;
  resize: none;
  border-radius: 5px;
   border: 1px solid #878787;
   height: 35px;
   font-family: 'Assistant';
    text-indent: 15px;
  font-size: 14pt;
}
.click {
  height: 100%;
  width: 100%;
}
</style>
<%= content_for :title , @user.name + "- Snapdshort" %>

<meta name="viewport" content="width=device-width" />

<div class = "about-user-container col-md-12 col-sm-12 col-xs-12">
  <div class = "about-user-picture-container col-md-offset-3 col-md-2 col-sm-2">
  <% if @user == current_user %>
  <%= link_to edit_picture_u_path(current_user), remote: true, method: :get do %>
    <div class = "after" data-toggle = "modal" data-target="#profilePicEditModal">
    
      
    </div>
    <% end %>
  <%end %>
  </div>
  <div class = "text-container col-md-5 col-sm-7 col-xs-12">
    <h2> <%= @user.name %> </h2> 
    <p> <% if @user.bio %>
          <%= @user.bio %>
        <% else %>
          Insert user tagline here 
        <% end %>
    <% if @user == current_user %>
      <%= link_to edit_tag_u_path(current_user), remote: true, method: :get do %>
        <i class="fa fa-pencil fa-lg" aria-hidden="true" data-toggle = "modal" data-target = "#tagEditModal"></i>
      <% end %>
    <% end %>
    </p> 
  </div>
</div>
<div class= "grid">
<div class = "grid-sizer"></div>
  <% @user.posts.each do |p| %>
  <div class = "grid-item">
    <a class= "mod-display" href ="#display-post">
      <div class = "mod-display-div" data-id="<%= p.id %>" id = "<%=dom_id(p)%>">
        <%= render partial: 'posts/post_user', locals: {post: p} %>
      </div>
    </a>
    </div>
  <% end %>
</div>

<%= render 'shared/modaldisplay' %>

<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      
      <div class="modal-body">
        <button type="button" class="btn btn-facebook btn-share" style="width: 100%"><i class="fa fa-facebook fa-lg" aria-hidden="true" style="margin: 5px"></i>facebook</button><br>
        <button type="button" class="btn btn-twitter btn-share" style="width: 100%"><i class="fa fa-twitter fa-lg" aria-hidden="true" style="margin-right: 5px"></i>twitter</button><br>
        <button type="button" class="btn btn-google-plus btn-share" style="width: 100%"><i class="fa fa-google-plus fa-lg" aria-hidden="true" style="margin-right: 5px"></i>Google +</button>
      </div>
    </div>
    </div>
  </div>
</div>

<div class="modal fade" id="tagEditModal" tabindex="-1" role="dialog" aria-labelledby="tagEditModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body">
        
      </div>
      
    </div>
  </div>
</div>

<div class="modal fade" id="profilePicEditModal" tabindex="-1" role="dialog" aria-labelledby="profilePicEditModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body">
        
      </div>
      
    </div>
  </div>
</div>

<script>
	var $grid = $('.grid');
$grid.imagesLoaded().progress( function() {
  $grid.masonry({
    itemSelector: '.grid-item',
  percentPosition: true,
  columnWidth: '.grid-sizer'
  });
});
$('.mod-display').animatedModal({
  modalTarget: 'display-post',
  color: '#f9f9f9'
});



$('.mod-display-div').on('click',function() {
  var thisPost = $(this);
  var postId = thisPost.data('id');
  var postUrl = '/posts/'+postId+'/post_content';
  $.ajax(postUrl, {
    type: 'get',
    data: {post: {id: postId}},
    dataType: 'json',
    success: function(result) {
      var title = '<h2>'+result.title+'</h2>';
      var content = result.content;
      var contentArray = content.split('\n');
      var modifiedContent = contentArray[0] + '<br>';
      for(var i = 1 ; i<contentArray.length;i++ ) {
        modifiedContent = modifiedContent + contentArray[i]+'<br>';
      }
      $('.post-title-container').html(title);
      $('.post-content-container').html('<p>'+modifiedContent+'</p>');
    }
  });
  var imageLink = thisPost.find('img').attr('src');
  $('.modal-picture-container').html("<img src ="+imageLink+" />");
});  
</script>

app/views/users/update.js.erb
location.reload();