config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              controllers: {registrations: 'users/registrations',
              :omniauth_callbacks => "users/omniauth_callbacks"}

  authenticated :user do 
    root :to => 'frames#archived', as: :authenticated_root
  end
  root 'pages#landing'
  resources :u, :controller => 'users' do
    get :edit_tag, on: :member
    get :edit_picture, on: :member 
  end
  get 'archived' => 'frames#archived'
  get 'signup' => 'pages#signup'
  get 'career' => 'pages#career'
  get 'team' => 'pages#team'
  get 'about' => 'pages#story'
  get 'search' => 'pages#search'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'landing' => 'pages#landing'
  get 'getting_started' => 'pages#getting_started'
  resources :posts do 
    get :post_content, on: :member
  end
  resources :frames
  resources :reports

  resources :likes, only: [:create,:destroy]

  get 'users/:user_id', to: 'posts#index', as: :abcd

end

app/views/pages/getting_started.html.erb
<style>
	.getting-started-img {
		height: 100%;
		width: auto;
		margin-left: 30px;
	}
</style>
<!DOCTYPE html>
<html>
<head>
	<title>Getting started</title>
</head>
<body>
	<div id="fullpage">
	<div class="section">
		<img src = "/assets/started1.png" class = "getting-started-img">
	</div>
	<div class="section">
		<img src = "/assets/started2.png" class = "getting-started-img">
	</div>
</div>
</body>
</html>


<script type="text/javascript">
	$(document).ready(function() {
	if ( $( 'html' ).hasClass( 'fp-enabled' ) ) {
  		$.fn.fullpage.destroy('all');
	}
	$('#fullpage').fullpage({
		sectionsColor : ['#CCFF90', '#FF8863']
	});
});
</script>

app/views/pages/landing.html.erb
<!--<style type="text/css">
	@media screen and (max-width: 1900px) {
		.title {
			font-size: 48px;
		}
		.center-title {
			margin-top: 175px;
		}
	}
	@media screen and (max-width: 420px) {
		.title {
			font-size: 40px;
		}
		.center-title {
			margin-top: 100px;
		}
	}
	body {
		background: #ffc400;
	}

	.center-title {
		text-align: center;
	}

	.title {
		font-family: 'Libre Baskerville';
		color: #fff;
	}

	.slogan {
		margin-top: 0px;
		font-size: 36px;
		color: #fff;
	}
	.user-links {
		float: right;

	}
	.user-links h3 {
		font-family: 'Quattrocento';
		color: #fff;
	}
	.user-links-list {
		list-style: none;
	}
	.user-links-list li {
		margin-left: 15px;
		margin-right: 25px;
		float: left;
	}
	a:hover , a:link, a:visited {
  text-decoration: none;
  color: #fff;
}
.play-button {
	color: #fff;
	font-size: 150px;
	font-family: 'Quattrocento';
}
.explore-button {
	color: #fff;
	font-family: 'Quattrocento';
	margin-top: 50px;
}
.fa-play {
	font-size: 100px;
}
.tutorial-video {
	width: 100%;
	height: 400px;
	border: 0px;
}

</style>
<% content_for :title , "Welcome to Snapdshort" %>
<div class = "user-links">
 <ul class = "user-links-list">
 	<li> 
 		<%= link_to new_user_session_path do %><h3> LOGIN </h3> <% end %>
 	</li>
 	<li> 
 		<%= link_to signup_path do %> <h3> SIGN UP </h3> <% end %> 
 	</li>
 </ul>
</div>
<div class = "center-title">
	<h1 class ="title"> SNAPDSHORT </h1>
	<h2 class = "slogan"> Sharing Stories. Shaping Lives. </h2><br>
	<span data-toggle = "modal" data-target = "#videoModal" ><h4 class = "play-button"> <i class="fa fa-play" aria-hidden="true"></i> </h4></span>
	<%= link_to frames_path do%><h1 class = "explore-button"> EXPLORE </h1><% end %>
</div>					
<div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <iframe class = "tutorial-video" src="https://www.youtube.com/embed/oD2WjSBUlZ4" allowfullscreen>
		</iframe>
      </div>
    </div>
  </div>
</div>	!-->
<style type="text/css">
		.main-logo-container {
		margin-left: 25%;
		margin-top: 5%;
	}

	.main-logo-container img {
		width: 600px;
		height: auto;
	}
	.landing-text-container {
	margin-left: 25%;
	width: 600px;
	font-family: Heebo;
}
.landing-text-container h1 {
	text-align: center;
}
</style>

<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link href="https://fonts.googleapis.com/css?family=Heebo:100" rel="stylesheet">
</head>
<body>
	<div class = "main-logo-container">
		<img src = "/assets/mainlogo.png">
	</div>
	<div class = "landing-text-container">
		<h1> Snapdshort is all about connections - identify a visual link and join the conversation! </h1>
	</div>
</body>
</html>

app/views/pages/search.html.erb
<style type="text/css">
	html { overflow-y: scroll; }

body { font-family: sans-serif; 
  
}

/* ---- grid ---- */

.grid {
  background: transparent;
  margin-top: 65px;
}

/* clear fix */
.grid:after {
  content: '';
  display: block;
  clear: both;
}

/* ---- .grid-item ---- */

.grid-sizer,
.grid-item {
  width: 33.333%;
}
@media screen and (max-width: 1224px) {
  .grid-sizer { width: 50%; }
  .grid-item { width: 50%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
    .close-display-post {
    color: gray;
  }
  
}


@media screen and (max-width: 720px) {
  .grid-sizer { width: 50%; }
  .grid-item { width: 50%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
  .close-display-post {
    color: #fff;
  }
  
  
}

@media screen and (max-width: 480px) {
  .grid-sizer { width: 100%; }
  .grid-item { width: 100%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
   .close-display-post {
    color: #fff;
  }
  
}

.grid-item {
  float: left;
  padding: 3px;
}

.grid-item img {
  display: block;
  max-width: 100%;
  border-top-right-radius: 1%;
  border-top-left-radius: 1%;
}

.grid-item a {
  text-decoration: none;
  color: black;
}

.card {
  border: 1px solid #ececec;
  border-radius: 1%;
  background: #ececec;
}

.card-block {
  background: #ececec;
  padding-bottom: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
.noselect {
  -webkit-touch-callout: none; /* iOS Safari */
  -webkit-user-select: none;   /* Chrome/Safari/Opera */
  -khtml-user-select: none;    /* Konqueror */
  -moz-user-select: none;      /* Firefox */
  -ms-user-select: none;       /* Internet Explorer/Edge */
  user-select: none; 
  user-drag: none; 
user-select: none;
-moz-user-select: none;
-webkit-user-drag: none;
-webkit-user-select: none;
-ms-user-select: none;          /* Non-prefixed version, currently
                                  not supported by any browser */
}

.modal-picture-container img{
  display: block;
  height: auto;
  width:100%;
}
.card-text {
  font-size: 1.2em;
}
.close-display-post {
  position: absolute;
  z-index: 10000;
  left: 95%;
  cursor: pointer;
  font-size: 2em;
}
</style>

<%= content_for :title, "Search Results" %>
<meta name="viewport" content="width=device-width" />
<div class= "grid">
<div class = "grid-sizer"></div>
<% @post.each do |p| %>
	<div class = "grid-item">
    <a class= "mod-display" href ="#display-post">
      <div class = "mod-display-div" data-id="<%= p.id %>" id = "<%=dom_id(p)%>">
        <%= render partial: 'posts/post', locals: {post: p} %>
      </div>
    </a>
    </div>
  <% end %>
</div>

<%= render 'shared/modaldisplay' %>

<script type="text/javascript">
	var $grid = $('.grid');
$grid.imagesLoaded().progress( function() {
  $grid.masonry({
    itemSelector: '.grid-item',
  percentPosition: true,
  columnWidth: '.grid-sizer'
  });
});  

$('.mod-display').animatedModal({
  modalTarget: 'display-post',
  color: '#f9f9f9'
});

$('.mod-display-div').on('click',function() {
  var thisPost = $(this);
  var postId = thisPost.data('id');
  var postUrl = '/posts/'+postId+'/post_content';
  $.ajax(postUrl, {
    type: 'get',
    data: {post: {id: postId}},
    dataType: 'json',
    success: function(result) {
      var title = '<h2>'+result.title+'</h2>';
      var content = result.content;
      var contentArray = content.split('\n');
      var modifiedContent = contentArray[0] + '<br>';
      for(var i = 1 ; i<contentArray.length;i++ ) {
        modifiedContent = modifiedContent + contentArray[i]+'<br>';
      }
      $('.post-title-container').html(title);
      $('.post-content-container').html('<p>'+modifiedContent+'</p>');
    }
  });
  var imageLink = thisPost.find('img').attr('src');
  $('.modal-picture-container').html("<img src ="+imageLink+" />");
});



</script>

app/views/pages/signup.html.erb
<style type="text/css">

	body {
		
	}
	 .btn-facebook {
  background-color: #3b5998;
}
@media screen and (max-width: 1900px) {
	.front-page {
		
	}
}

@media screen and (max-width: 480px) {
	.front-page {
		
	}
}
.btn-login{
  margin: 10px;
  color: #fff;
  font-family: 'Heebo', sans-serif;
  width: 100%;
}
.btn-login:hover {
  color: #fff;
}
.btn-login:focus {
  color: #fff;
  outline: none;
}

.slogan {
	margin-top: 50px;
}
.signup h2 {
	text-align: center;
}
.create-account-button {
	background: #ecf0f1;
	font-size: 17px;
}
.signup h3 {
	padding: 0px;
}
.back-button {
  font-family: 'Heebo';
  color: #fff;
  margin-top: -15px;
  padding-left: 15px;
  cursor: pointer;
}
.signup {
	font-family: 'Heebo';
}


</style>
<html>
<head>
	<link href="https://fonts.googleapis.com/css?family=Heebo:100" rel="stylesheet">
</head>
<body>
	<% skip_footer = true %>
	<% content_for :title , "Sign up | Snapdshort" %>
	<div class = "row front-page">
	
		<div class ="col-md-4 col-sm-5 col-xs-12 col-md-offset-4 col-sm-offset-3 signup">
			<h2 style="color:black">SIGN UP</h2>
			<div class = "form">
				<%= form_for(User.new, as: :user, url: registration_path(resource_name)) do |f| %>
					<%= f.text_field :name, placeholder: "Name", :required => true%><br />
					<%= f.email_field :email , placeholder: "Email", :required => true%><br />
					<%= f.password_field :password , placeholder: "Password", :required => true, :pattern => ".{8,}" , id: "pass-input"%><br />
					<%= f.password_field :password_confirmation , placeholder: "Confirm your password", :required => true, :pattern => ".{8,}", id: "pass-confirm-input"%><br />
					<%= f.submit "Create" ,class: "create-account-button"%>
				<% end %>
			</div>
			<h3 style="color:black"> Or sign up using</h3>
				<a href = '/users/auth/facebook'>
				<button type="button" class="btn btn-facebook btn-login" style="width: 80%"><i class="fa fa-facebook fa-lg" aria-hidden="true" style="margin: 5px"></i>facebook</button>
				</a>
		</div>
	</div>
	</body>
	</html>

	<script type="text/javascript">
	var password = document.getElementById('pass-input');
		var confirm_password = document.getElementById('pass-confirm-input');
		function validatePasswordLength() {
			if (password.value.length < 8) {
				password.setCustomValidity("Password must be at least 8 characters long");
			} else {
				password.setCustomValidity('');
			}
		}
		password.onchange = validatePasswordLength;
		password.onkeyup = validatePasswordLength;


		
		function validatePassword() {
			if (password.value != confirm_password.value) {
				confirm_password.setCustomValidity("Passwords don't match");
			} else {
				confirm_password.setCustomValidity('');
			}
		}
		password.onchange = validatePassword;
		confirm_password.onkeyup = validatePassword;



	</script>

app/views/pages/team.html.erb
<meta name="viewport" content="width=device-width" />
<meta name="theme-color" content="#4EB980">
<style type="text/css">
* { box-sizing: border-box; }
::selection{
  background: yellow;
}

/* force scrollbar */
html { overflow-y: scroll; }

body { font-family: sans-serif; 
  
}

/* ---- grid ---- */

.grid {
  background: transparent;
}

/* clear fix */
.grid:after {
  content: '';
  display: block;
  clear: both;
}

/* ---- .grid-item ---- */

.grid-sizer,
.grid-item {
  width: 33.333%;
}
@media screen and (max-width: 1224px) {
  .grid-sizer { width: 50%; }
  .grid-item { width: 50%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
  
}


@media screen and (max-width: 720px) {
  .grid-sizer { width: 50%; }
  .grid-item { width: 50%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
  
}

@media screen and (max-width: 480px) {
  .grid-sizer { width: 100%; }
  .grid-item { width: 100%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
  
}

.grid-item {
  float: left;
  padding: 3px;
}

.grid-item img {
  display: block;
  max-width: 100%;
  border-top-right-radius: 1%;
  border-top-left-radius: 1%;
}

.grid-item a {
  text-decoration: none;
  color: black;
}

.card {
  border: 1px solid #ececec;
  border-radius: 1%;
  background: #ececec;
}

.card-block {
  background: #ececec;
  padding-bottom: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
.noselect {
  -webkit-touch-callout: none; /* iOS Safari */
  -webkit-user-select: none;   /* Chrome/Safari/Opera */
  -khtml-user-select: none;    /* Konqueror */
  -moz-user-select: none;      /* Firefox */
  -ms-user-select: none;       /* Internet Explorer/Edge */
  user-select: none; 
  user-drag: none; 
user-select: none;
-moz-user-select: none;
-webkit-user-drag: none;
-webkit-user-select: none;
-ms-user-select: none;          /* Non-prefixed version, currently
                                  not supported by any browser */
}
.modal-picture-container img{
  display: block;
  height: auto;
  width:100%;
}



</style>


<h1>Masonry - imagesLoaded progress</h1>

<div class="grid">
  <div class="grid-sizer"></div>
  <div class="grid-item">
    <a class= "mod-display" href ="#display-post">
    <div class="card">
      <img class= "card-img-top noselect" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/orange-tree.jpg" />
      <div class="card-block">
        <h3 class="card-title">Card title</h3>
        <h6 class="card-subtitle text-muted">Support card subtitle</h6>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="card-footer text-muted">
          2 days ago
      </div>
      </div>
    </div></a>
  </div>
  <div class="grid-item">
  <a class= "mod-display" href ="#display-post">
    <div class="card">
      <img class="card-img-top noselect" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/submerged.jpg" />
      <div class="card-block">
        <h3 class="card-title">Card title</h3>
        <h6 class="card-subtitle text-muted">Support card subtitle</h6>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="card-footer text-muted">
          2 days ago
      </div>
      </div>
    </div></a>
  </div>
  <div class="grid-item">
  <a class= "mod-display" href ="#display-post">
    <div class="card">
      <img class="card-img-top noselect" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/look-out.jpg" />
      <div class="card-block">
        <h3 class="card-title">Card title</h3>
        <h6 class="card-subtitle text-muted">Support card subtitle</h6>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="card-footer text-muted">
          2 days ago
      </div>
      </div>
    </div></a>
  </div>
  <div class="grid-item">
  <a class= "mod-display" href ="#display-post">
    <div class="card">
      <img class="card-img-top noselect" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/one-world-trade.jpg" />
      <div class="card-block">
        <h3 class="card-title">Card title</h3>
        <h6 class="card-subtitle text-muted">Support card subtitle</h6>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="card-footer text-muted">
          2 days ago
      </div>
      </div>
    </div></a>
  </div>
  <div class="grid-item">
  <a class= "mod-display" href ="#display-post">
    <div class="card">
      <img class="card-img-top noselect" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/drizzle.jpg" />
      <div class="card-block">
        <h3 class="card-title">Card title</h3>
        <h6 class="card-subtitle text-muted">Support card subtitle</h6>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="card-footer text-muted">
          2 days ago
      </div>
      </div>
    </div>
  </div></a>
  <div class="grid-item">
  <a class= "mod-display" href ="#display-post">
    <div class="card">
      <img class="card-img-top noselect" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/cat-nose.jpg" />
      <div class="card-block">
        <h3 class="card-title">Card title</h3>
        <h6 class="card-subtitle text-muted">Support card subtitle</h6>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="card-footer text-muted">
          2 days ago
      </div>
      </div>
    </div></a>
  </div>
  <div class="grid-item">
  <a class= "mod-display" href ="#display-post">
    <div class="card">
      <img class="card-img-top noselect" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/contrail.jpg" />
      <div class="card-block">
        <h3 class="card-title">Card title</h3>
        <h6 class="card-subtitle text-muted">Support card subtitle</h6>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="card-footer text-muted">
          2 days ago
      </div>
      </div>
    </div></a>
  </div>
  <div class="grid-item">
  <a class= "mod-display" href ="#display-post">
    <div class="card">
      <img class="card-img-top noselect" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/golden-hour.jpg" />
      <div class="card-block">
        <h3 class="card-title">Card title</h3>
        <h6 class="card-subtitle text-muted">Support card subtitle</h6>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="card-footer text-muted">
          2 days ago
      </div>
      </div>
    </div></a>
  </div>
  <div class="grid-item">
  <a class= "mod-display" href ="#display-post">
    <div class="card">
      <img class="card-img-top noselect" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/82/flight-formation.jpg" />
      <div class="card-block">
        <h3 class="card-title">Card title</h3>
        <h6 class="card-subtitle text-muted">Support card subtitle</h6>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <div class="card-footer text-muted">
          2 days ago
      </div>
      </div>
    </div>
  </div></a>
</div>

<div id="display-post">
            <!--"THIS IS IMPORTANT! to close the modal, the class name has to match the name given on the ID-->
    <div  id="btn-close-modal" class="close-display-post"> 
                CLOSE MODAL
    </div>
            
    <div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12 modal-picture-container">
    </div>

    <div class = "col-md-12 col-xs-12 col-sm-12 modal-content-container">
      <div class = "post-title-container">
        <h2> Lorem Ispum </h2>
      </div>
      <div class = "post-content-container">
        <p>Lorem ipsum dolor sit amet, ei usu voluptua moderatius necessitatibus. Ut vix tollit invenire rationibus, hinc natum zril sed te. Mei verterem iracundia definitiones eu, cu reque fugit putent pro. Quot tation denique vis te. Et integre cotidieque his, te has quidam veritus. Duo justo libris perpetua ex, sea et clita honestatis.

Vix cu malis antiopam sapientem. Eos dicat falli ullamcorper at, quo id quodsi molestie repudiare. Vel primis forensibus ex, id nec periculis intellegat, rebum vidisse cum ex. His in omnes iisque. Te brute cotidieque mea.

Id sed eius augue recteque. Mei omnis theophrastus ne. Ius no reque consequat, simul option mandamus ad est, nec et nulla commodo. Ex ignota tincidunt pro. Ne facilis urbanitas mea, ornatus vituperatoribus mel an, pri delenit nonumes insolens an. Eum ut odio nusquam.

Nec veritus percipit delicatissimi et, pri te epicurei incorrupte. Adhuc mandamus quo no, principes honestatis his et. Sea ad omnes saperet. Quot signiferumque ius cu. Qui novum laboramus definitiones in, ei eos suscipit adolescens dissentias. Quo quot audiam cu, has et nostrud convenire, nihil oporteat dissentiet ea duo. Ius quod quodsi consequuntur no, ne legendos democritum duo.</p>
      </div>
    </div>

    <div class = "col-md-12 col-xs-12 col-sm-12 modal-about-container">
      <h3> About the author </h3>
    </div>

</div>

<script type="text/javascript">
var $grid = $('.grid');
$grid.imagesLoaded().progress( function() {
  $grid.masonry({
    itemSelector: '.grid-item',
  percentPosition: true,
  columnWidth: '.grid-sizer'
  });
});  

$('.mod-display').animatedModal({
  modalTarget: 'display-post',
  color: '#f9f9f9'
});

$('.mod-display').on('click',function() {
  var thisPost = $(this);
  var imageLink = thisPost.find('img').attr('src');
  $('.modal-picture-container').html("<img src ="+imageLink+" />");
});

</script>