config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
              controllers: {registrations: 'users/registrations',
              :omniauth_callbacks => "users/omniauth_callbacks"}

  authenticated :user do 
    root :to => 'frames#archived', as: :authenticated_root
  end
  root 'pages#landing'
  resources :u, :controller => 'users' do
    get :edit_tag, on: :member
    get :edit_picture, on: :member 
  end
  get 'archived' => 'frames#archived'
  get 'signup' => 'pages#signup'
  get 'career' => 'pages#career'
  get 'team' => 'pages#team'
  get 'about' => 'pages#story'
  get 'search' => 'pages#search'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'landing' => 'pages#landing'
  get 'getting_started' => 'pages#getting_started'
  resources :posts do 
    get :post_content, on: :member
  end
  resources :frames
  resources :reports

  resources :likes, only: [:create,:destroy]

  get 'users/:user_id', to: 'posts#index', as: :abcd

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :frame
	has_many :likes
	has_many :liking_users, through: :likes, source: :user
	mount_uploader :picture, PictureUploader
	validates :content,	presence: true,
						length: {maximum: 5000}
	validates :picture, presence: true
	validates :title, presence: true
	
	acts_as_taggable

	


	def self.search(params)
		Post.tagged_with(params,any: true, wild: true)
	end

	def update_frame 
		fr = self.frame;
		fr.cluster_update = DateTime.now.utc();
		fr.save;
	end

	private 
	def picture_size 
		if(picture.size > 5.megabytes)
			errors.add(:picture, "should be less than 5 MB")
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:show,:index,:post_content]
	before_action :find_current_user, except: [:show]

	def index
		if params[:tag]
			@post = Post.tagged_with(params[:tag])
		elsif params[:user_id]
			@user = User.find(params[:user_id])
			@post = @user.posts
		elsif user_signed_in?
			@post = @user.posts 
		else
			redirect_to new_user_session_path
		end
	end

	def new
		@post = @user.posts.new
	end

	def create
		@post = @user.posts.new(post_params)
		if @post.save
			@post.update_frame
			respond_to do |format|
				format.js 
			end
		else
			redirect_to new_post_path
		end
	end

	def edit
		@post = @user.posts.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		respond_to do |format|
			if @post.update(post_params) 
				format.js
			end
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy!
	end

	def show
		@post = Post.find(params[:id])
	end

	def post_content
		@post = Post.find(params[:id])

		respond_to do |format|
			format.json {render json: @post.to_json(only: [:content,:title])}
		end
	end

	private 

	def find_current_user
		@user = current_user
	end 

	def post_params 
		params.require(:post).permit(:content,:picture,:tag_list,:frame_id, :title,:user_id,:link)
	end
	
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_resource_name
		Post.new
	end

	def post_resource_class
		Post
	end

	def post_resource 
		@post_resource ||= Post.new
	end
end

app/views/posts/_edit_post.html.erb
<%= form_for post, remote: true do |f| %>
	<%= f.text_area :title , class: "edit-post-title"%>
	<%= f.text_area :content, class: "edit-post-content" %>

	<div class = "modal-footer">
		<%= f.submit "Save changes" , class: "btn btn-primary edit-save-button" %>
		<button type="button" class="btn btn-secondary edit-close-button" data-dismiss="modal">Close</button>
	</div>
<% end %>

app/views/posts/_post.html.erb
<style>
.card-title, .card-text {
  padding-left: 15px;
}
.card {
  border-radius: 0px;
  box-shadow: 1.5px 1.5px 1px #adadad;
}
.card-img-top img{
  border-radius: 0px;
}
.tag-btn {
  height: 20px;
  line-height: 5px;
}
.card-tags {
  padding-left: 15px;
}
.share-btn {
  position: absolute;
  z-index: 111;
  top: 4%;
  left: 90%;

  text-align: center;
  opacity: 0.8;
}

.share-btn:hover {
  opacity: 0.5;
  transition: 0.1s;
}
.fa-share-alt {
  color: #fff;
}
</style>

<div class="card">
  
    <div class = "card-img">
      <a href = "javascript:void(0)" class = 'share-btn' data-toggle="modal" data-target=".bs-example-modal-sm"><i class="fa fa-share-alt fa-lg" aria-hidden="true"></i></a>
      <a class= "mod-display" href ="#display-post">
        <%= image_tag post.picture.url , class:"card-img-top noselect"%>
      </a>
    </div>
    <div class = "card-block">
        <a class= "mod-display" href ="#display-post">
          <h3 class = "card-title"><%= post.title %></h3>
          <p class = "card-text"><%= post.content[0..100] %>...</p>
        </a>
        <p class = "card-tags">
          <% tags = post.tags %>
          <% tags.each do |t| %>
              <%= link_to tag_path(t.name),method: :get do%>
                <button type="button" class="btn btn-info btn-sm tag-btn">
                
                  <span style="font-family: 'Assistant';"><%= t.name %></span>
              </button>
              <% end %>
          <% end %>
        </p>
        <div class = "card-footer text-muted">
        <% if user_signed_in? %>
          <% if current_user.liked?(post) %>
            <%= link_to like_path(post_id: post.id, id: current_user.id), remote: true, method: :delete do%>
              <i class="fa fa-heart fa-lg heart-btn" aria-hidden="true"></i>
            <% end %>
          <% else %>
            <%= link_to likes_path(post_id: post.id), remote: true, method: :post do %>
              <i class="fa fa-heart-o fa-lg heart-btn" aria-hidden="true"></i>
            <% end %>
          <% end %>
          <span style = "font-family: 'Assistant', sans-serif"><%= post.liking_users.count %></span>
          <%= link_to post, method: :delete, remote: true, data: {confirm: "Are ya sure?"} do %>
            <i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>
          <% end %>
          <i class="fa fa-flag fa-lg" aria-hidden="true" style="float:right" data-toggle = "modal" data-target = "#reportModal"></i>
          <span data-toggle="tooltip" data-placement="bottom" title="Permalink" style="float:right">
            <%= link_to post do%>
              <i class="fa fa-code fa-lg" aria-hidden="true" style="float:right"></i>
            <% end %>
          </span>
          <% end %>
        </div>
     </div>
</div>

<script type="text/javascript">
  $('.share-btn').click(function(event) {
    event.preventDefault();
  });
</script>

app/views/posts/_post_user.html.erb
<!--<style>
.card-title, .card-text {
  padding-left: 15px;
}
.card {
  border-radius: 0px;
  box-shadow: 1.5px 1.5px 1px #adadad;
}
.card-img-top img{
  border-radius: 0px;
}
.tag-btn {
  height: 20px;
  line-height: 5px;
}
.card-tags {
  padding-left: 15px;
}
.share-btn {
  position: absolute;
  z-index: 111;
  top: 4%;
  left: 90%;

  text-align: center;
  opacity: 1;
}

.share-btn:hover {
  opacity: 1;
  transition: 0.1s;
}
.fa-share-alt {
  color: #fff;
}
.card-author {
  font-family: 'Quattrocento',serif;
  font-weight: bold;
  padding-left: 15px;
  font-size: 1.2em;
}
.fa-flag {
  color: red;
}

.card-block {
  border-right: 1px solid gray;
  padding-top: 10px;
}
.card-title {
  margin-top: 10px;
}
.link-btn {
  background: #1abc9c;
  border: 1px solid #1abc9c;
}
.link-btn:active {
  background: #1abc9c;
  border: 1px solid #1abc9c;
}
.link-btn:hover {
  background: #1abc9c;
  border: 1px solid #1abc9c;
}
.link-btn:focus {
  background: #1abc9c;
  border: 1px solid #1abc9c;
}
.card-img img {
  display: block;
  max-width: 100%;
  border-top-right-radius: 0px;
  border-top-left-radius: 0px;
  width: 100%;
}
.card-timestamp {
  padding-left: 15px;
  font-family: 'Assistant';
}
</style>

<div class="card">
  
    <div class = "card-img">
      <a href = "javascript:void(0)" class = 'share-btn' data-toggle="modal" data-target=".bs-example-modal-sm"><i class="fa fa-share-alt fa-lg" aria-hidden="true"></i></a>
      <a class= "mod-display" href ="#display-post">
        <%= image_tag post.picture.url(:crop) , class:"card-img-top noselect"%>
      </a>
    </div>
    <div class = "card-block">
        <a class= "mod-display" href ="#display-post">
          <h3 class = "card-title"><%= post.title %> <span style = "font-family:'Assistant'; font-size: 15px;">by</span>
            <%= link_to u_path(post.user)  do%> 
              <span style = "font-size: 17px;font-weight: bold"><%= post.user.name %></span>
            <% end %>
          </h3>
          <p class = "card-text"><%= post.content[0..200] %>...</p>
        </a>
        <p class = "card-timestamp"> <%= post.created_at.strftime("%B %d, %Y") %> </p>
        <p class = "card-tags">
          <% tags = post.tags %>
          <% tags.each do |t| %>
              <%= link_to tag_path(t.name),method: :get do%>
                <button type="button" class="btn btn-info btn-sm tag-btn">
                
                  <span style="font-family: 'Assistant';"><%= t.name %></span>
              </button>
              <% end %>
          <% end %>
          <% if post.link %>
           <button type = "button" class="btn btn-info btn-sm tag-btn link-btn">
                <%= post.link %>
            </button>
          <% end %>
        </p>
        <div class = "card-footer text-muted">
          <% if user_signed_in? %>
            <span class = "card-like-container">
            	<% if current_user.liked?(post) %>
                <%= link_to like_path(post_id: post.id), remote: true, method: :delete do%>
                  <i class="fa fa-heart fa-lg heart-btn" aria-hidden="true"></i>
                <% end %>
              <% else %>
                <%= link_to likes_path(post_id: post.id), remote: true, method: :post do %>
                  <i class="fa fa-heart-o fa-lg heart-btn" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </span>
            <span class = "likes-count-container" style = "font-family: 'Assistant', sans-serif"><%= post.liking_users.count %></span>
            <% if post.user == current_user || current_user.admin%>
                <%= link_to post, method: :delete, remote: true, data: {confirm: "Are ya sure?"} do %>
              	 <i class="fa fa-times-circle-o fa-lg" aria-hidden="true"></i>
                <% end %>
                <%= link_to edit_post_path(post), remote: true do %>
                  <i class="fa fa-pencil fa-lg" aria-hidden="true" data-toggle = "modal" data-target = "#editPostModal"></i>
                <% end %>
            <% end %>
            <span class= "flag-post" data-toggle = "tooltip" data-placement="bottom" title="Report" style = "float:right">
              <i class="fa fa-flag fa-lg" aria-hidden="true" style="float:right" data-toggle = "modal" data-target = "#reportModal"></i>
            </span>
            <span class= "permalink" data-toggle="tooltip" data-placement="bottom" title="Permalink" style="float:right">
              <%= link_to post, method: :get do%>
                <i class="fa fa-code fa-lg" aria-hidden="true" style="float:right"></i>
              <% end %>
            </span>
          <% end %>
        </div>
     </div>
</div>

<script type="text/javascript">
$(document).on('turbolinks:load', function() {
  $('.share-btn').click(function(event) {
    event.preventDefault();
  });

  $('.permalink').tooltip({ container: 'body' });
  $('.flag-post').tooltip({ container: 'body' });

});
</script>!-->

<style>
  #img-main {
    width: 50%;
    box-shadow: -25px -25px #CCFF90;
  }
  .img-div {
    margin: 100px;
  }

  .img-text-1 {
    
    font-family: 'Heebo';
    font-size: 24px;
  }

  .img-text-div {
    
    width: 400px;
  }

 

  .link-btn {
    background-color: #1abc9c;
    border: none;
  }

  a:hover , a:visited, a:active {
    text-decoration: none;
    color: black;
  }
  a {
    text-decoration: none;
    color: black;
  }
 
</style>
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Heebo:100" rel="stylesheet">
</head>
<body>
  <div class = "img-div">
    <%= image_tag post.picture.url(:crop), id:"img-main" %>
    <div class = "img-text-div">
      <p class = "img-text-1"><%= post.content[0..250] %>...</p>
      <div class = "img-tag">
        <button type="button" class="btn btn-info btn-sm tag-btn theme-btn"> <%= post.frame.tags.first %> </button>
        <% if post.link %>
          <button type="button" class="btn btn-info btn-sm tag-btn link-btn"> <%= post.link%> </button>
        <%end%>
    </div>
  </div>
</div>
</body>
</html>

app/views/posts/create.js.erb
$('.modal-body').html('<p>The form was successfully submitted<p>');
$('.submit-button').hide();
location.reload();

app/views/posts/destroy.js.erb
location.reload();

app/views/posts/edit.js.erb
var bodyForm = $('#editPostModal').find('.modal-body');
bodyForm.html('<%= j render partial: "posts/edit_post", locals: {post: @post} %>');

app/views/posts/index.html.erb
<style>
 html { overflow-y: scroll; }

body { font-family: sans-serif; 
  
}

/* ---- grid ---- */

.grid {
  background: transparent;
  margin-top: 0px;
}

/* clear fix */
.grid:after {
  content: '';
  display: block;
  clear: both;
}

/* ---- .grid-item ---- */

.grid-sizer,
.grid-item {
  width: 33.333%;
}
@media screen and (max-width: 1224px) {
  .grid-sizer { width: 50%; }
  .grid-item { width: 50%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
  
}


@media screen and (max-width: 720px) {
  .grid-sizer { width: 50%; }
  .grid-item { width: 50%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
  
}

@media screen and (max-width: 480px) {
  .grid-sizer { width: 100%; }
  .grid-item { width: 100%; }
  .col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
  
}

.grid-item {
  float: left;
  padding: 3px;
}

.grid-item img {
  display: block;
  max-width: 100%;
  border-top-right-radius: 1%;
  border-top-left-radius: 1%;
}

.grid-item a {
  text-decoration: none;
  color: black;
}

.card {
  border: 1px solid #ececec;
  border-radius: 1%;
  background: #ececec;
}

.card-block {
  background: #ececec;
  padding-bottom: 10px;
  padding-left: 10px;
  padding-right: 10px;
}
.noselect {
  -webkit-touch-callout: none; /* iOS Safari */
  -webkit-user-select: none;   /* Chrome/Safari/Opera */
  -khtml-user-select: none;    /* Konqueror */
  -moz-user-select: none;      /* Firefox */
  -ms-user-select: none;       /* Internet Explorer/Edge */
  user-select: none; 
  user-drag: none; 
user-select: none;
-moz-user-select: none;
-webkit-user-drag: none;
-webkit-user-select: none;
-ms-user-select: none;          /* Non-prefixed version, currently
                                  not supported by any browser */
}
.modal-picture-container img{
  display: block;
  height: auto;
  width:100%;
}  

.about-user-container {
  background-color: transparent;
}

.about-user-picture-container {
  height: 200px;
  width: 200px;
  background-image: url(http://1.gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=280);
   background-size: cover;
    background-repeat: no-repeat;
    border-radius: 100%;
}

.text-container {
  margin-left: 65px;
}

.card-text {
  font-size: 1.2em;
}

</style>
<h1> Hello <%= current_user.id %> </h1>
<!-- TODO: 
	1. Put script code in asset pipeline
	2. Change div to ul, li for proper display
	3. If posstible, add data attributes and use those to display the data when the user clicks on a div.
	4. change some names
 -->
 <meta name="viewport" content="width=device-width" />
<div class= "grid">
<div class = "grid-sizer"></div>
  <% @post.each do |p| %>
  <div class = "grid-item">
    <a class= "mod-display" href ="#display-post">
      <div class = "mod-display-div" data-id="<%= p.id %>" id = "<%=dom_id(p)%>">
        <%= render partial: 'posts/post', locals: {post: p} %>
      </div>
    </a>
    </div>
  <% end %>
</div>

 <%= render 'shared/modaldisplay' %>

	
<script>

var $grid = $('.grid');
$grid.imagesLoaded().progress( function() {
  $grid.masonry({
    itemSelector: '.grid-item',
  percentPosition: true,
  columnWidth: '.grid-sizer'
  });
});  

$('.mod-display').animatedModal({
  modalTarget: 'display-post',
  color: '#f9f9f9'
});


$('.mod-display-div').on('click',function() {
  var thisPost = $(this);
  var postId = thisPost.data('id');
  var postUrl = '/posts/'+postId+'/post_content';
  $.ajax(postUrl, {
    type: 'get',
    data: {post: {id: postId}},
    dataType: 'json',
    success: function(result) {
      var title = '<h2>'+result.title+'</h2>';
      var content = result.content;
      var contentArray = content.split('\n');
      var modifiedContent = contentArray[0] + '<br>';
      for(var i = 1 ; i<contentArray.length;i++ ) {
        modifiedContent = modifiedContent + contentArray[i]+'<br>';
      }
      $('.post-title-container').html(title);
      $('.post-content-container').html('<p>'+modifiedContent+'</p>');
    }
  });
  var imageLink = thisPost.find('img').attr('src');
  $('.modal-picture-container').html("<img src ="+imageLink+" />");
});
	
	
</script>

app/views/posts/new.html.erb
<%= form_for(@post, html: { multipart: true }) do |f| %>
	<%= f.text_field :content %>
	<%= f.file_field :picture %>
	<%= f.text_field :tag_list, 'data-role'=>'tagsinput' %>
	<%= f.submit "submit" %>
<% end %>

app/views/posts/show.html.erb
<style type="text/css">
	@media screen and (max-width: 1224px) {
		.col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
}

@media screen and (max-width: 720px) {
	.col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
  
}

@media screen and (max-width: 480px) {
	.col-sm-12 {padding-left: 0px;
    padding-right: 0px;
  }
  .col-xs-12 {
    padding-left: 0px;
    padding-right: 0px;
  }
  
}
.modal-picture-container {
  margin-top: 65px;
}
.modal-picture-container img{
  display: block;
  height: auto;
  width:100%;
}  
.post-divider {
  width: 50%;
  color: black;
  background: black;
}
</style>
<meta property="og:url" content = "<%= request.original_url %>">
<meta property="og:title" content="<%= @post.title %>" >
<meta property="og:image" content="<%= @post.picture.url%>" >
<meta property="og:description" content="<%= @post.content[0..100] %>">
<meta property="twitter:url" content = "<%= request.original_url %>">
<meta property="twitter:title" content="<%= @post.title %>" >
<meta property="twitter:image" content="<%= @post.picture.url%>" >
<meta property="twitter:description" content="<%= @post.content[0..100] %>">
<% content_for :title , @post.title + " | Snapdshort" %>

<div class="col-md-8 col-md-offset-2 col-sm-12 col-xs-12 modal-picture-container">
	<%= image_tag @post.picture.url %>
</div>

 <div class = "col-md-12 col-xs-12 col-sm-12 modal-content-container">
      <div class = "post-title-container">
        <h2> <%=@post.title  %></h2>
      </div>
      <div class = "post-content-container">
        <p><%= @post.content %></p>
      </div>
    </div>

<hr class = "post-divider">

app/views/posts/update.js.erb
location.reload();